# Generated by Django 5.1.1 on 2025-09-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'uuid'], 'verbose_name': ['Service'], 'verbose_name_plural': 'Serices'},
        ),
    ]
