# Generated by Django 5.2.6 on 2025-09-18 10:24

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', 'uuid'], 'verbose_name': ['Service'], 'verbose_name_plural': ['Services']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='service',
            name='collaborators',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='collaborator'),
        ),
        migrations.AddField(
            model_name='service',
            name='collectd_ips',
            field=models.BooleanField(default=True, verbose_name='collected ips'),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='service',
            name='hide_referrer_regex',
            field=models.TextField(blank=True, default='', validators=[core.models._validate_regex], verbose_name='Hide referrer regex'),
        ),
        migrations.AddField(
            model_name='service',
            name='ignore_robots',
            field=models.BooleanField(default=False, verbose_name='ignore robots'),
        ),
        migrations.AddField(
            model_name='service',
            name='ignored_ips',
            field=models.TextField(blank=True, default='', validators=[core.models._validate_regex], verbose_name='ignored ips'),
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='service',
            name='origins',
            field=models.TextField(default='*', verbose_name='origins'),
        ),
        migrations.AddField(
            model_name='service',
            name='respect_dnt',
            field=models.BooleanField(default=True, verbose_name='respect dnt'),
        ),
        migrations.AddField(
            model_name='service',
            name='script_inject',
            field=models.TextField(blank=True, default='', verbose_name='script inject'),
        ),
        migrations.AddField(
            model_name='service',
            name='statuses',
            field=models.CharField(choices=[('AC', 'Active'), ('AR', 'Archived')], db_index=True, default='AC', max_length=2, verbose_name='statuses'),
        ),
        migrations.AddField(
            model_name='service',
            name='uuid',
            field=models.UUIDField(default=core.models._default_uuid, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=core.models._default_uuid, max_length=84, unique=True, verbose_name='username'),
        ),
    ]
