# Generated by Django 5.1.1 on 2025-09-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_service_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='statuses',
            new_name='status',
        ),
    ]
