# Generated by Django 5.1.1 on 2025-09-20 07:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_statuses_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ignored_ips',
            field=models.TextField(blank=True, default='', validators=[core.models._valid_network_list], verbose_name='ignored ips'),
        ),
    ]
