# Generated by Django 5.1.1 on 2025-09-18 13:18

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField(db_index=True, default=False, verbose_name='initial')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='start time')),
                ('last_seen', models.DateTimeField(auto_now=True, null=True, verbose_name='last seen')),
                ('heartbeats', models.IntegerField(default=0, verbose_name='heartbeats')),
                ('tracker', models.CharField(choices=[('JS', 'JavaScript'), ('PIXEL', 'Pixel (noscript)')], default='JS', max_length=10, verbose_name='tracker')),
                ('location', models.TextField(blank=True, db_index=True, verbose_name='location')),
                ('referrer', models.TextField(blank=True, db_index=True, verbose_name='referrer')),
                ('load_time', models.CharField(db_index=True, max_length=50, null=True, verbose_name='load time')),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=analytics.models._default_uuid, verbose_name='uuid')),
                ('identifier', models.TextField(blank=True, verbose_name='identifier')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='start time')),
                ('last_seen', models.DateTimeField(auto_now=True, null=True, verbose_name='last seen')),
                ('user_agent', models.CharField(max_length=50, null=True, verbose_name='user agent')),
                ('browser', models.CharField(max_length=50, null=True, verbose_name='browser')),
                ('devices', models.CharField(max_length=50, null=True, verbose_name='devices')),
                ('device_type', models.CharField(choices=[('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('ROBOT', 'Robot'), ('OTHER', 'Other')], default='OTHER', max_length=7, verbose_name='Device type')),
                ('os', models.TextField(null=True, verbose_name='operating system')),
                ('ip', models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP')),
                ('asn', models.TextField(blank=True, verbose_name='asn')),
                ('country', models.TextField(null=True, verbose_name='country')),
                ('longitude', models.FloatField(null=True, verbose_name='longitude')),
                ('latitude', models.FloatField(null=True, verbose_name='latitude')),
                ('time_zone', models.CharField(db_index=True, max_length=100, null=True, verbose_name='time zone')),
                ('is_bounce', models.BooleanField(default=False, verbose_name='is bounce')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
