# Generated by Django 5.2.6 on 2025-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000, verbose_name='path')),
                ('referrer', models.CharField(blank=True, max_length=50, null=True, verbose_name='referrer')),
                ('user_agent', models.CharField(blank=True, verbose_name='user agent')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='ip hash')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='time stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, verbose_name='session key')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='first seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='last seen')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='hits')),
            ],
        ),
    ]
