# Generated by Django 5.2.6 on 2025-09-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='service hit'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='hit',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.session', verbose_name='session hit'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['service', 'timestamp'], name='analytics_h_service_c5735e_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session'], name='analytics_h_session_077d33_idx'),
        ),
    ]
