# Generated by Django 5.1.1 on 2025-09-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.service', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='hit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.session', verbose_name='session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', '-start_time'], name='analytics_s_service_4b1137_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', '-last_seen'], name='analytics_s_service_10bb96_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', 'identifier'], name='analytics_s_service_82ab21_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', '-start_time'], name='analytics_h_session_b2667f_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['service', '-start_time'], name='analytics_h_service_f4f41e_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'location'], name='analytics_h_session_775f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'referrer'], name='analytics_h_session_98b8bf_idx'),
        ),
    ]
